### ISSUE TITLE
ethereum.utils

### ISSUE THREAD

**Issue by Dmitriy-17** [seevik2580/ethereum-wallet-recovery#1]
C:\ethereum-wallet-recovery-master-new-test>python louskac.py -p UTC--2017-07-12T00-06-42.772050600Z--f5751c906091b98be2a6be5ce42c573d704aedab -z start.txt -w wordlist_01.txt
Traceback (most recent call last):
  File "louskac.py", line 3, in <module>
    from keys import decode_keystore_json
  File "C:\ethereum-wallet-recovery-master-new-test\keys.py", line 6, in <module>
    from ethereum.utils import encode_hex
ImportError: No module named ethereum.utils

**Comment by seevik2580** [comment]
python modules to require: pbkdf2 rlp ethereum joblib

**Comment by pi4a** [comment]
hello.
how to change generator, so you can generate generic passwords from 12 characters?
