### ISSUE TITLE
help

### ISSUE THREAD

**Issue by pi4a** [seevik2580/ethereum-wallet-recovery#2]
hello.
how to change generator, so you can generate generic passwords from 12 characters?

**Comment by seevik2580** [comment]
i did update, now you can specify lenght min/max 
`python generuj.py -min 8 -s "1,2,3,4,5,6,7,8,9,0"`
# generate all permutations of words 1,2,3,4,5,6,7,8,9,0 with minimal lenght 8. less lenght is skipped.

[](https://github.com/seevik2580/ethereum-wallet-recovery/commit/38c343c8f3129797bc3bcd5203766777cc1a5b8b?diff=split)

**Comment by pi4a** [comment]
Thank you
