### ISSUE TITLE
Generating combinations with -min and -max

### ISSUE THREAD

**Issue by sullronn** [seevik2580/ethereum-wallet-recovery#4]
Hello, generating combinations with the keys -min&-max work only with numbers?
Could you add this functions to generation all combinations in the file?

**Comment by seevik2580** [comment]
-min -max should work with all combinations.
generuj.py -a -min 1 -max 5
generuj.py -s "words,separated,by,comma" -min 5 -max 15
generuj.py -v input.txt -min 10 -max 80
all generated combinations are saved into wordlist_01.txt, if file is greater than 50MB then it will split to next file wordlist_02.txt
if -max is not specified then max is 64 chars length, but you can do -max 9999999 if you wish.

**Comment by sullronn** [comment]
Don't actually so. Maybe only for me.
What I do:
generuj.py -v psw.txt -min 10 -max 25
(1,2,..0,!,@,#..,),Ge,Jambo,jambo,...etc) words contain with 8-9-10 symbols.
After script done (about 2-3 sec) I have file wordlist_01.txt with 2804 combinations.
All combinations started with symbols (0,1, etc).
Neither one combinations are not started with  - !, 2,3 or another words.
Quantity symbols, numbers, and words in psw.txt an equally 46.
Too little all combinations for a source.
All symbols just summarise per line after each.
No mixed combinations.
Very strange.

**Comment by sullronn** [comment]
Now, I had done an experiment:
python generuj.py -v input.txt -min 5 -max 20
Generuji variace hesel
wordlist_01.txt 0.000350952148438
Hotovo, vygenerovano 50 kombinaci
Vytvoreno 1 souboru

File wordlist_01.txt in attach.
Neither combinations not started with 42 - for example.
[wordlist_01.txt](https://github.com/seevik2580/ethereum-wallet-recovery/files/2009181/wordlist_01.txt)

**Comment by seevik2580** [comment]
wow, you are absolutely right i must overlooked it when i run tests.
i fixed it with just removing two lines of code.. you can now download fixed version of generuj.py or
just remove two lines in generuj.py down from `print "Generuji", myfile.c,". heslo" `

```
else:
     break
```
commit [5ba0b21](https://github.com/seevik2580/ethereum-wallet-recovery/commit/5ba0b2116bd1fa5ba135ec57b1eb516d2e8e2685?diff=split)

**Comment by sullronn** [comment]
Sorry! Routine has swallowed me) Yep, now this is working well :) Thank you!
