### ISSUE TITLE
Ubuntu 20.04 faulty commands E: Unable to locate package python-pip

### ISSUE THREAD

**Issue by europound** [seevik2580/ethereum-wallet-recovery#7]
sudo apt-get install python-pip python-dev libssl-dev build-essential automake pkg-config libtool libffi-dev libgmp-dev pandoc
[sudo] password for wallets:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
E: Unable to locate package python-pip

**Comment by seevik2580** [comment]
hello, it's almost 5y old script based on ubuntu 12.x .. to make it work with ubuntu 20.04+ i recommend you to use pyenv to install python 2.7.14 + pip

```
curl https://pyenv.run | bash
echo 'export PATH="~/.pyenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(pyenv init -)" ' >> ~/.bashrc
echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
exec $SHELL
pyenv install 2.7.14
pyenv global 2.7.14
pip install setuptools --upgrade
pip install joblib
pip install pypandoc
pip install markdown
pip install rlp==0.6.0
pip install py_ecc==1.1.3
pip install ethereum==2.1.5
```
then it works fine

**Comment by europound** [comment]
wallets@wallets-TUF-Gaming:~/Downloads/ethereum-wallet-recovery-master$ pip install passlib
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting passlib
  Downloading passlib-1.7.4-py2.py3-none-any.whl (525 kB)
     |████████████████████████████████| 525 kB 373 kB/s 
Installing collected packages: passlib
Successfully installed passlib-1.7.4
WARNING: You are using pip version 20.3.3; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
wallets@wallets-TUF-Gaming:~/Downloads/ethereum-wallet-recovery-master$ python louskac.py -p UTC--2017-07-12T00-06-42.772050600Z--f5751c906091b98be2a6be5ce42c573d704aedab -b 1234567890 -d 2
Traceback (most recent call last):
  File "louskac.py", line 3, in <module>
    from keys import decode_keystore_json
  File "/home/wallets/Downloads/ethereum-wallet-recovery-master/keys.py", line 2, in <module>
    import pbkdf2
ImportError: No module named pbkdf2
wallets@wallets-TUF-Gaming:~/Downloads/ethereum-wallet-recovery-master$
